### ISSUE TITLE
After "ionic emulate android" gives me that error

### ISSUE THREAD

**Issue by softwareengineer111** [juarezpaf/secret-santa-app#1]
"Error: cannot read property 'length' of undefined"

That's working on Browser with no problem :D

**Comment by juarezpaf** [comment]
@negdim sorry for this huge delay. Finally taking a look at this project again. Will ping you 🔜

**Comment by softwareengineer111** [comment]
Thanks Guys. You are so Awesome :D :D :D

**Comment by juarezpaf** [comment]
@negdim I just fixed a bunch of things. Please clone the project again, follow the instructions to get the project up and running and then... `ionic cordova run android`

Happy coding!
